### ISSUE TITLE
Struggling to install on Ubuntu

### ISSUE THREAD

**Issue by samcov** [wasienv/wasienv#2]
**Tried**: curl https://github.com/wasienv/wasienv/raw/master/install.sh -L| sh

**Result**:
> Successfully installed wasmer 0.8.0!
wasmer & wapm will be available the next time you open the terminal.
If you want to have the commands available now please execute:
source /home/samcov/.wasmer/wasmer.sh

> Installing the required WASI SDKs
sh: 32: **wasienv: not found**

Then tried:
pip install wasienv --upgrade
wasienv install-sdk unstable

**Result**: wasienv: command not found

Any suggestions?

**Comment by syrusakbary** [comment]
Hi @samcov,

This is probably due to the Python/pip binaries not being in the environment `$PATH`.
Are you using a virtual environment by any chance?

**Comment by samcov** [comment]
Yes, I'm in VMWare.

**Comment by syrusakbary** [comment]
Thanks for the report!

We just updated the installation script to fix that issue!
https://github.com/wasienv/wasienv/commit/1984e395af875563d28e8e7879181d56d51f7fff

If you can try again and report if it worked, that would be awesome!

Closing the issue meanwhile

**Comment by samcov** [comment]
Tried it again, and PERFECTION! The output of the compilation and running it are shown below.

**This is the easiest, most productive environment for generating WASM I've seen... Congratulations!**

samcov@samcov-virtual-machine:~/Dev/Wasm$ ls
example.c
samcov@samcov-virtual-machine:~/Dev/Wasm$ wasicc example.c -o example
In file included from <built-in>:1:
/home/samcov/.local/lib/python2.7/site-packages/wasienv/stubs/preamble.h:40:62: warning: declaration of 'struct sigaction' will not be visible outside of this function [-Wvisibility]
__attribute__((weak)) int sigaction(int signum, const struct sigaction *act,
                                                             ^
1 warning generated.
samcov@samcov-virtual-machine:~/Dev/Wasm$ ls
example  example.c  example.wasm

samcov@samcov-virtual-machine:~/Dev/Wasm$ ./example Sam
Hello, Sam!

**Comment by samcov** [comment]
BTW, I also tweeted about this: https://twitter.com/Dewey2000/status/1195239005496823809
![Untitled](https://user-images.githubusercontent.com/1551314/68924777-6148a280-0736-11ea-9ab7-a8b51c8a8859.jpg)
