### ISSUE TITLE
Issues with Installing on Ubuntu

### ISSUE THREAD

**Issue by torch2424** [wasienv/wasienv#20]
Hello @syrusakbary ! :smile: So I was working on a talk in my free time, and found some issues when using a fresh installation of PopOS!(Ubuntu):

1. This requires python 3 or greater to work. And in Ubuntu 18.04, Python 2 was installed by default. And when you install python3, the command becomes `python3`. Thus, I think it'd be good to mention to Ubuntu users to install Python3 using [pyenv](https://github.com/pyenv/pyenv). That way wasienv installs correctly.
2. On Ubuntu 18.04, `cmake` isn't installed by default. Thus it'd be good to recommend that it should be installed with: `sudo apt install cmake`.

Hope that helps! :smile: :+1:

**Comment by syrusakbary** [comment]
Thanks for opening the issue @torch2424!

Wasienv should work with Python 2. In fact, we are already testing Python 2, Python 3 and Pypy in the CI ( https://github.com/wasienv/wasienv/blob/master/.github/workflows/main.yml#L11 )

Could be possible to know how installation was failing in your machine?

> On Ubuntu 18.04, cmake isn't installed by default. Thus it'd be good to recommend that it should be installed with: sudo apt install cmake.

Good call! Although wasienv only requires cmake if you are going to build a cmake project (like quickjs). We should mention it though, just in case is useful for the user

**Comment by torch2424** [comment]
@syrusakbary Ah yes, maybe the stars were not aligning with python 2 on my machine :joy: 

And for cmake, good point! :+1: 

I'll just go ahead and close this issue than. Thanks for taking a look! :smile:
