### ISSUE TITLE
Support SDK 10

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasienv/wasienv#24]
[WASI SDK 10] was just published, we should support it 

[WASI SDK 10]: https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-10

**Comment by vshymanskyy** [comment]
Is this as easy as https://github.com/wasienv/wasienv/pull/15/files ?

**Comment by MarkMcCaskey** [comment]
@vshymanskyy Yeah, the PR itself is simple, I'll make one now!  Then we just need to publish a new version of the python package
