### ISSUE TITLE
Installing WasiEnv requires pip

### ISSUE THREAD

**Issue by torch2424** [wasienv/wasienv#6]
This should be mentioned on the README in the installation section 😄 

<img width="638" alt="Screen Shot 2019-10-31 at 11 11 38 AM" src="https://user-images.githubusercontent.com/1448289/67974242-55ee6680-fbcf-11e9-961f-165b9d02b3aa.png">

**Comment by o-micron** [comment]
`on a side note` pip has now been removed from Debian and Ubuntu (20.04).

Moving to `Python3` and `Pip3` is needed now 😃

![Screenshot from 2020-04-25 20-04-22](https://user-images.githubusercontent.com/44799922/80284544-7d0d9700-871f-11ea-93f0-fe8d39f97373.png)

**Comment by vshymanskyy** [comment]
Bump.

**Comment by vshymanskyy** [comment]
@syrusakbary maybe you could take a look?
I was able to install wasienv by replacing `pip` with `pip3` in the `install.sh` (locally).

**Comment by torch2424** [comment]
Thank you @syrusakbary ! :smile:
